@startuml

title __CONTROLLERS's Class Diagram__\n

  namespace  {
    namespace ain.java {
      namespace Controllers {
        class main.java.Controllers.AccessibilityOptionsController {
            + AccessibilityOptionsController()
            + addressRequest()
            + deleteRequest()
            + getAllRequest()
            + rejectRequest()
            + save()
            + sendRequest()
        }
      }
    }
  }
  

  namespace  {
    namespace ain.java {
      namespace Controllers {
        class main.java.Controllers.AttendeeMenuController {
            - role : String
            - username : String
            + AttendeeMenuController()
            + addRequest()
            + addRoom()
            + createEvent()
            + createUser()
            + downloadScheduleTxt()
            + downloader()
            + getListOfAttendees()
            + getRequests()
            + homepage()
            + manageFriendsList()
            + menuSelection()
            + messageAttendees()
            + modifyCapacity()
            + organizerMessageAll()
            + removeEvent()
            + scheduleSpeaker()
            + sendMessage()
            - adminSwitch()
            - attendeeSwitch()
            - cancelEnrolEvent()
            - organizerSwitch()
            - signUpEvent()
            - speakerSwitch()
        }
      }
    }
  }
  

  namespace  {
    namespace ain.java {
      namespace Controllers {
        class main.java.Controllers.MessageController {
            # inbox : HashMap<String, ArrayList<Message>>
            # messageString : String
            # outbox : HashMap<String, ArrayList<Message>>
            # receiver : String
            # sender : String
            + MessageController()
            + MessageController()
            + deleteMessage()
            + getAllMessages()
            + getMessageForMe()
            + getMessagesFromSender()
            + getMessagesToReceiverFromSender()
            + saveMessages()
            + sendMessage()
            + setMessageString()
            + setMessageSystem()
            + setReceiver()
            + setSender()
            - allMessageHelper()
        }
      }
    }
  }
  

  namespace  {
    namespace ain.java {
      namespace Controllers {
        class main.java.Controllers.OrganizerMessageController {
            - organizer : String
            + OrganizerMessageController()
            + toAllAttendee()
            + toAllSpeaker()
            + toOneAttendee()
            + toOneSpeaker()
        }
      }
    }
  }
  

  namespace  {
    namespace ain.java {
      namespace Controllers {
        class main.java.Controllers.ProgramMain {
            + ProgramMain()
            + close()
            + newUserUsernamePrompt()
            + passwordPrompt()
            + start()
            - askRole()
            - askUserType()
            - login()
            - register()
            - retUserUsernamePrompt()
        }
      }
    }
  }
  

  main.java.Controllers.AccessibilityOptionsController o-- main.java.UseCases.AccessibilityOptionsCreator : requestCreator
  main.java.Controllers.AccessibilityOptionsController o-- main.java.Gateways.AccessibilityOptionsGateway : requestList
  main.java.Controllers.AttendeeMenuController o-- main.java.Controllers.AccessibilityOptionsController : accessibility
  main.java.Controllers.AttendeeMenuController o-- main.java.UseCases.BuildingManager : building
  main.java.Controllers.AttendeeMenuController o-- main.java.UseCases.EventManager : eventManager
  main.java.Controllers.AttendeeMenuController o-- main.java.Presenters.UserMenu : menu
  main.java.Controllers.AttendeeMenuController o-- main.java.UseCases.UserManager : userManager
  main.java.Controllers.MessageController o-- main.java.Gateways.MessageGateway : allMessages
  main.java.Controllers.MessageController o-- main.java.UseCases.MessageCreator : messageSystem
  main.java.Controllers.MessageController o-- main.java.Gateways.UserLoginGateway : userLoginGateway
  main.java.Controllers.ProgramMain .up.|> java.lang.AutoCloseable
  main.java.Controllers.ProgramMain o-- main.java.Controllers.AccessibilityOptionsController : accessibility
  main.java.Controllers.ProgramMain o-- main.java.UseCases.BuildingManager : buildingManager
  main.java.Controllers.ProgramMain o-- main.java.UseCases.EventManager : eventManager
  main.java.Controllers.ProgramMain o-- main.java.UseCases.UserManager : userManager


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
