@startuml

title __PRESENTERS's Class Diagram__\n

  namespace  {
    namespace ain.java {
      namespace Presenters {
        class main.java.Presenters.StartingMenu {
            + alreadyRegistered()
            + failedPrompt()
            + initialPrompt()
            + loggedInPrompt()
            + newUserCreated()
            + pPrompt()
            + passwordResetSuccess()
            + resetPasswordPrompt()
            + rolePrompt()
            + uPrompt()
            + usernameNotFoundPrompt()
            + usernameUsed()
            + welcome()
            + wrongPasswordPrompt()
            + wrongRole()
        }
      }
    }
  }
  

  namespace  {
    namespace ain.java {
      namespace Presenters {
        class main.java.Presenters.UserMenu {
            + adminMade()
            + attendeeMade()
            + awaitResponse()
            + cancelEnrolStatus()
            + createEventCapacity()
            + createEventDay()
            + createEventDuration()
            + createEventHour()
            + createEventMinute()
            + createEventMonth()
            + createEventName()
            + createEventRoom()
            + createEventYear()
            + createRoomCapacity()
            + createRoomEnd()
            + createRoomName()
            + createRoomStart()
            + createSpeakerName()
            + createUserName()
            + createUserType()
            + deleteMessagePrompt()
            + displayEventsWithNoAttendees()
            + downloadFailed()
            + downloadLocationNotSelected()
            + downloadSuccess()
            + enterEvent()
            + enterEventID()
            + enterRequestNum()
            + enterUsername()
            + eventPrompt()
            + friendsList()
            + friendsListUsername()
            + invalidID()
            + invalidResponse()
            + logoutSuccess()
            + manageEvent()
            + modifyEventCapacity()
            + operationComplete()
            + optionsAdmin()
            + optionsAttendee()
            + optionsOrganizer()
            + optionsSpeaker()
            + organizerMade()
            + printAttendees()
            + printBuildingSchedule()
            + printMessages()
            + printSomething()
            + promptagainonly()
            + request()
            + requestAction()
            + scheduleDownload()
            + selectAnotherOption()
            + sendMessageContent()
            + sendMessageUser()
            + signUpEventStatus()
            + speakerMade()
            + viewAllMessages()
            + viewSpeakerEvents()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
